### ISSUE TITLE
dracut module 'dmsquash-live' cannot be found or installed

### ISSUE THREAD

**Issue by chazy-chaz** [chadmed/asahi-gentoosupport#20] opened 2024-03-30 08:08 UTC
Hi
Asahi Linux switched to Fedora and the genstrap.sh script gives the error: dracut module 'dmsquash-live' cannot be found or installed

**Comment by chadmed** [comment] 2024-04-25 01:22
This should be fixed now. The issue is that Fedora's dracut defaults to `-H` which prevents anything not explicitly required by the host system from being loaded.

**Closed as completed by chadmed** 2024-04-25 01:22 UTC
